# Generated by Django 6.0.2 on 2026-02-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_slot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
